# Generated by Django 3.0.5 on 2021-06-11 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='institutionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ed.Institution'),
        ),
    ]
